USE OrderFlowDb;
GO

CREATE TABLE Clientes
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) NOT NULL,
    Telefone NVARCHAR(20) NULL,
    CriadoEm DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO