USE OrderFlowDb;
GO

CREATE TABLE Produtos
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    Descricao NVARCHAR(300) NULL,
    Preco DECIMAL(18,2) NOT NULL,
    Estoque INT NOT NULL,
    Ativo BIT NOT NULL DEFAULT 1,
    CriadoEm DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO